//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourRaidingBuddy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YourRaidingBuddy.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconCloseRound {
            get {
                object obj = ResourceManager.GetObject("IconCloseRound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconInfo {
            get {
                object obj = ResourceManager.GetObject("IconInfo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconKeyboard {
            get {
                object obj = ResourceManager.GetObject("IconKeyboard", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconKnife {
            get {
                object obj = ResourceManager.GetObject("IconKnife", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconSettings {
            get {
                object obj = ResourceManager.GetObject("IconSettings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconShield {
            get {
                object obj = ResourceManager.GetObject("IconShield", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconWizard {
            get {
                object obj = ResourceManager.GetObject("IconWizard", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;R4GE&lt;/title&gt;
        ///&lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;div style=&quot;text-align: center; font-weight: bold; font-family: Segoe UI; font-size: small; color: #B22222;&quot;&gt;
        ///            Thank you for purchasing YourRaidingBuddy III - Premium!
        ///        &lt;/div&gt;
        ///        &lt;br/&gt;
        ///        &lt;div style=&quot;font-family: Segoe UI; font-size: small; color: dimgray;&quot;&gt;
        ///            If you encounter issues with this routine, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StoreLogo {
            get {
                object obj = ResourceManager.GetObject("StoreLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yrb_logo {
            get {
                object obj = ResourceManager.GetObject("yrb_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;YRB2&gt;
        ///  &lt;Version&gt;4.5.08&lt;/Version&gt;
        ///  &lt;AuraList&gt;
        ///    &lt;Spell Id=&quot;145171&quot; Name=&quot;MC spell Garrosh (final phase empowered)&quot; /&gt;
        ///    &lt;Spell Id=&quot;145065&quot; Name=&quot;MC spell Garrosh (P2)&quot; /&gt;
        ///    &lt;Spell Id=&quot;145175&quot; Name=&quot;MC Spell Garrosh (unknown)&quot; /&gt;
        ///    &lt;Spell Id=&quot;145071&quot; Name=&quot;MC Spell Garrosh (unknown)&quot; /&gt;
        ///  &lt;/AuraList&gt;
        ///&lt;/YRB2&gt;.
        /// </summary>
        internal static string YRB3Aura {
            get {
                return ResourceManager.GetString("YRB3Aura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;YRB2&gt;
        ///  &lt;Version&gt;4.5.08&lt;/Version&gt;
        ///  &lt;InterruptList&gt;
        ///    &lt;Spell Id=&quot;145171&quot; Name=&quot;MC spell Garrosh (final phase empowered)&quot; /&gt;
        ///    &lt;Spell Id=&quot;145065&quot; Name=&quot;MC spell Garrosh (P2)&quot; /&gt;
        ///    &lt;Spell Id=&quot;145175&quot; Name=&quot;MC Spell Garrosh (unknown)&quot; /&gt;
        ///    &lt;Spell Id=&quot;145071&quot; Name=&quot;MC Spell Garrosh (unknown)&quot; /&gt;
        ///    &lt;Spell Id=&quot;145599&quot; Name=&quot;MC Spell Garrosh (unknown)&quot; /&gt;
        ///    &lt;Spell Id=&quot;136797&quot; Name=&quot;Dino-Mending (ToT)&quot; /&gt;
        ///    &lt;Spell Id=&quot;136587&quot; Name=&quot;Venom Bolt Volley (T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YRB3Interrupt {
            get {
                return ResourceManager.GetString("YRB3Interrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;YRB2&gt;
        ///  &lt;Version&gt;4.5.08&lt;/Version&gt;
        ///  &lt;AuraList&gt;
        ///    &lt;Spell Id=&quot;155198&quot; Name=&quot;BeastLord : Savage Howl&quot; /&gt;
        ///    &lt;Spell Id=&quot;155173&quot; Name=&quot;Blast Furence : Reactive Earth Shield&quot; /&gt;
        ///  &lt;/AuraList&gt;
        ///&lt;/YRB2&gt;.
        /// </summary>
        internal static string YRB3Tranq {
            get {
                return ResourceManager.GetString("YRB3Tranq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;YRB2&gt;
        ///  &lt;Version&gt;4.5.08&lt;/Version&gt;
        ///  &lt;UnitList&gt;
        ///    &lt;Unit Id=&quot;145171&quot; Name=&quot;MC Unit Garrosh (final phase empowered)&quot; /&gt;
        ///    &lt;Unit Id=&quot;145065&quot; Name=&quot;MC Unit Garrosh (P2)&quot; /&gt;
        ///  &lt;/UnitList&gt;
        ///&lt;/YRB2&gt;.
        /// </summary>
        internal static string YRB3Unit {
            get {
                return ResourceManager.GetString("YRB3Unit", resourceCulture);
            }
        }
    }
}
